import Head from "next/head";

import { ContributionContainer, Header } from "../../components";

const Contribution = () => {
  return (
    <div className="w-full">
      <Head>
        <title>Alat For Corporative</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <Header pageName={"Transactions"} subPageName={"Contribution"} />
        <ContributionContainer />
      </div>
    </div>
  );
};

export default Contribution;
