import Head from "next/head";
import Image from "next/image";
import { RiLockPasswordLine } from "react-icons/ri";
import { AiOutlineMail } from "react-icons/ai";

const AlmostThere = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen  text-center">
      <Head>
        <title>Alat For Corporative</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col w-full flex-1">
        <div className="flex w-full h-screen bg-dark-purple justify-center relative">
          <img
            src="/new-bg.png"
            alt="Alat for Cooperative"
            className="w-full h-full object-cover absolute mix-blend-soft-light bg-opacity-5"
          />
          <div className="flex p-16 flex-col absolute w-5/12 text-center justify-center items-center">
            <Image
              src="/logo.png"
              alt="Alat for Cooperative"
              width={75}
              height={75}
            />
            <div className="bg-white w-5/6  mt-10 p-10 py-14 rounded-md text-left">
              <div>
                <h2 className="text-3xl font-bold mb-4 text-dark-purple">
                  You are almost there!
                </h2>
                <p className="text-gray-500">
                  Login with email address and password in the email you
                  received
                </p>
              </div>
              <div className="mt-6">
                <label className="font-semibold w-full">Email Address</label>
                <div className="bg-gray-100  p-2 flex mb-3 mt-3">
                  <AiOutlineMail className="text-gray-400 m-2" />
                  <input
                    type="email"
                    name="email"
                    placeholder="Enter account number"
                    className="bg-gray-100 outline-none text-sm flex-1"
                  />
                </div>
              </div>
              <div className="mt-6">
                <label className="font-semibold w-full">Email Address</label>
                <div className="bg-gray-100  p-2 flex mb-3 mt-3">
                  <RiLockPasswordLine className="text-gray-400 m-2" />
                  <input
                    type="password"
                    name="password"
                    placeholder="Password"
                    className="bg-gray-100 outline-none text-sm flex-1"
                  />
                </div>
              </div>
              <a
                className="bg-light-purple text-gray-300 rounded-md w-full px-12 py-2 text-center mt-5 inline-block font-semibold hover:bg-dark-purple hover:text-white"
                href="">
                Continue
              </a>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default AlmostThere;
