import Head from "next/head";

import { ChatContainer, Header } from "../components";

const Files = () => {
  return (
    <div className="w-full">
      <Head>
        <title>Alat For Corporative</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <Header pageName={"Files"} subPageName={"Files"} />
        {/* <ChatContainer /> */}
        <div className="h-screen flex items-center justify-center">
          Files Coming Soon
        </div>
      </div>
    </div>
  );
};

export default Files;
