import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useMutation } from "react-query";
import { useRouter } from "next/router";

import notification from "../utilities/notification";
import handleFetch from "../services/api/handleFetch";

const Home = () => {
  const router = useRouter();
  const [accountNumber, setAccountNumber] = useState("");
  const [buttonDisabled, setButtonDisabled] = useState(true);

  const handleAccountChange = (event) => {
    setAccountNumber(event.target.value);
    setButtonDisabled(!event.target.value);
    setButtonDisabled(event.target.value.length < 10);
  };

  const validateMutation = useMutation(handleFetch, {
    onSuccess: (res) => {
      if (res?.statusCode === 201) {
        router?.push({pathname: '/success',
        query: { email: res?.data?.email }});
        notification({
          title: "Email Sent",
          message:
            "We've sent an onboading link to your mail, please check your mail.",
          type: "success",
        });
      } 
    },
    onError: (err) => {
      notification({
        title: "Error",
        message: err?.toString() || "Something went wrong.",
        type: "danger",
      });
    },
  });
  
  const handleVerify = (e) => {
    e.preventDefault();
    if (accountNumber.length < 10) {
      notification({
        title: "Form Error",
        message: "Please, enter a valid account number",
        type: "danger",
      });
      return;
    }
    validateMutation.mutate({
      endpoint: "auth",
      extra: "validate-accountNumber",
      method: "POST",
      body: { accountNumber },
    });
  };

  const { isLoading } = validateMutation;

  return (
    <div className="flex flex-col items-center justify-center min-h-screen  text-center">
      <Head>
        <title>Alat For Corporative</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-new.ico" />
      </Head>
      <main className="flex flex-col w-full flex-1">
        <div className="flex w-full h-screen ">
          <div className="w-3/6 bg-gradient-to-b  from-transparent to-dark-purple relative">
            <Image
              src="/bg.jpg"
              alt="Alat for Cooperative"
              className="w-full h-full object-cover absolute mix-blend-overlay bg-opacity-5"
              width={1000}
              height={1000}
              priority
            />
            <div className="p-16">
              <Image
                src="/logo.png"
                alt="Alat for Cooperative"
                width={75}
                height={75}
              />
              <div className="mt-auto absolute bottom-20 ">
                <p className="text-white inline-block font-semibold text-left w-full mb-4">
                  Join Us Today
                </p>
                <h1 className="text-5xl font-bold text-white w-4/6 text-left leading-[52px]">
                  Get started on ALAT for Cooperative Platform
                </h1>
              </div>
            </div>
          </div>
          <div className="w-3/6 bg-white py-56 px-40 text-left">
            <div className="max-w-md">
              <h2 className="text-3xl font-bold mb-2 text-dark-purple">
                Create Account
              </h2>
              <p className="mb-12 w-full text-gray-500">
                Create an account using your existing cooperative Wema account
                number
              </p>
              <div>
                <label className="font-semibold">Wema Account Number</label>
                <div className="bg-input-fill w-full p-2 flex rounded-md items-center mb-3 mt-4 border border-input-outline">
                  <input
                    type="number"
                    name="accountNumber"
                    value={accountNumber}
                    onChange={handleAccountChange}
                    label="accountNumber"
                    placeholder="Enter account number"
                    className="bg-input-fill outline-none text-sm flex-1 h-8 sm:w-full"
                  />
                </div>
              </div>
              <button
                className={`${
                  buttonDisabled && "bg-light-purple text-gray-300"
                } rounded-md w-full sm:w-full sm:px-6 px-12 py-2 text-center mt-8 inline-block font-semibold ${
                  !buttonDisabled &&
                  "hover:bg-dark-purple hover:text-white border border-dark-purple text-dark-purple"
                }`}
                type="submit"
                disabled={buttonDisabled}
                onClick={handleVerify}
              >
                {isLoading ? "Loading..." : "Verify Account"}
              </button>
              <p className="mt-3 font-semibold text-xs text-center">
                Already have an account?{" "}
                <Link href="/login" className="text-dark-purple font-bold">
                  Sign in here
                </Link>
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
