import Head from "next/head";
import Image from "next/image";
import Link from 'next/link';
import { RiLockPasswordLine, } from "react-icons/ri";
import { AiOutlineMail } from "react-icons/ai";

const Login = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen text-center">
    <Head>
      <title>Alat For Corporative</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="flex flex-col w-full flex-1">
      <div className="flex w-full justify-center relative">
        <img
          src="/new-bg.png"
          alt="Alat for Cooperative"
          className="w-full object-cover absolute bg-dark-purple"
        />
          <div className="flex p-16 flex-col absolute w-5/12 text-center justify-center items-center">
            <Link href="/">
            <Image
              src="/logo.png"
              alt="Alat for Cooperative"
              width={75}
              height={75}
            />
            </Link>
            <div className="bg-white w-5/6  mt-10 p-10 py-14 rounded-md text-left">
              <div>
                <h2 className="text-3xl font-bold mb-4 text-dark-purple">
                  Log in
                </h2>
                <p className="text-gray-500">
                  Continue to your cooperative account
                </p>
              </div>
              <div className="mt-6">
                <label className="font-semibold w-full">Email Address</label>
                <div className="p-2 flex mb-3 mt-3 rounded-md border border-input-outline bg-input-fill">
                  <AiOutlineMail className="text-gray-400 m-2" />
                  <input
                    type="email"
                    name="email"
                    placeholder="Email Address"
                    className="bg-input-fill outline-none text-sm flex-1"
                  />
                </div>
              </div>
              <div className="mt-6">
                <label className="font-semibold w-full">New Password</label>
                <div className="p-2 flex mb-3 mt-3 rounded-md border border-input-outline bg-input-fill">
                  <RiLockPasswordLine className="text-gray-400 m-2" />
                  <input
                    type="password"
                    name="password"
                    placeholder="Password"
                    className="bg-input-fill outline-none text-sm flex-1"
                  />
                </div>
              </div>
              <Link
                className="text-dark-purple w-full  inline-block font-semibold text-sm"
                href="/forgotpassword">
                Forgot Password?
              </Link>
              <Link
                className="bg-light-purple text-gray-300 rounded-md w-full px-12 py-2 text-center mt-8 inline-block font-semibold hover:bg-dark-purple hover:text-white"
                href="/dashboard">
                Login
              </Link>
              <p className="mt-3 font-semibold text-xs text-center">
              New Here?{"  "}
              <Link href="">
              <span className="text-dark-purple font-bold">Get started</span>
              </Link>
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Login;
