import Head from "next/head";

import { SettingContainer, Header } from "../components";

const Setting = () => {
  return (
    <div className="w-full">
      <Head>
        <title>Alat For Corporative</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <Header pageName={"Settings"} subPageName={"Account Settings"} />
        <SettingContainer />
      </div>
    </div>
  );
};

export default Setting;
