import Head from "next/head";
import Image from "next/image";
import { IoMdCheckmarkCircleOutline } from "react-icons/io";

const Success = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen  text-center">
      <Head>
        <title>Alat For Corporative</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col w-full flex-1">
        <div className="flex w-full h-screen">
          <div className="w-3/6 bg-gradient-to-b from-transparent to-dark-purple relative">
            <img
              src="/bg.jpg"
              alt="Alat for Cooperative"
              className="w-full h-full object-cover absolute mix-blend-overlay bg-opacity-5"
            />
            <div className="p-16">
              <Image
                src="/logo.png"
                alt="Alat for Cooperative"
                width={75}
                height={75}
              />
              <div className="mt-auto absolute bottom-20 ">
                <p className="text-white inline-block font-semibold text-left w-full mb-4">
                  Join Us Today
                </p>
                <h1 className="text-5xl font-bold text-white w-4/6 text-left leading-[51px]">
                  Get started on ALAT for Cooperative Platform
                </h1>
              </div>
            </div>
          </div>
          <div className="w-3/6 bg-white py-56 px-40 text-center">
            <IoMdCheckmarkCircleOutline className="text-green-500 w-full text-4xl mb-4" />
            <h2 className="text-3xl font-bold mb-12 text-dark-purple">
              Success!
            </h2>
            <p className="w-full text-gray-500 text-center">
              An email has been sent to{" "}
              <span className="font-bold text-dark-alat-purple">lapo@gmail.com.</span> Kindly check
              and follow the steps to activate your account.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Success;

Success.getLayout = function PageLayout(page){
  return <>{page}</> 
}
