export const MOCK_DATA = [
    {
      id: 1,
      "S/N": 1,
      DATE: "20 Feb, 2023 @5:30am",
      "TRANSACTION ID": "TR-637153993...",
      "BANK NAME": {
        BANK_NAME: "ALATbyWema",
        BANK_IMAGE: "/bank-logo/alat.jfif",
      },
      "ACCOUNT NUMBER": 2190404040,
      "ACCOUNT NAME": "Oladapo John",
      AMOUNT: "₦200,000",
      STATUS: "Pending",
      "RAISED BY": "David John",
    },
    {
      id: 2,
      "S/N": 2,
      DATE: "20 Feb, 2023 @5:30am",
      "TRANSACTION ID": "TR-637153993...",
      "BANK NAME": {
        BANK_NAME: "ALATbyWema",
        BANK_IMAGE: "/bank-logo/alat.jfif",
      },
      "ACCOUNT NUMBER": 2190404040,
      "ACCOUNT NAME": "Oladapo John",
      AMOUNT: "₦200,000",
      STATUS: "Failed",
      "RAISED BY": "David John",
    },
    {
      id: 3,
      "S/N": 3,
      DATE: "20 Feb, 2023 @5:30am",
      "TRANSACTION ID": "TR-637153993...",
      "BANK NAME": {
        BANK_NAME: "Access",
        BANK_IMAGE: "/bank-logo/access.png",
      },
      "ACCOUNT NUMBER": 2190404040,
      "ACCOUNT NAME": "Oladapo John",
      AMOUNT: "₦200,000",
      STATUS: "Failed",
      "RAISED BY": "David John",
    },
    {
      id: 4,
      "S/N": 4,
      DATE: "20 Feb, 2023 @5:30am",
      "TRANSACTION ID": "TR-637153993...",
      "BANK NAME": {
        BANK_NAME: "Access",
        BANK_IMAGE: "/bank-logo/access.png",
      },
      "ACCOUNT NUMBER": 2190404040,
      "ACCOUNT NAME": "Oladapo John",
      AMOUNT: "₦200,000",
      STATUS: "Pending",
      "RAISED BY": "David John",
    },
    {
      id: 5,
      "S/N": 5,
      DATE: "20 Feb, 2023 @5:30am",
      "TRANSACTION ID": "TR-637153993...",
      "BANK NAME": {
        BANK_NAME: "Access",
        BANK_IMAGE: "/bank-logo/access.png",
      },
      "ACCOUNT NUMBER": 2190404040,
      "ACCOUNT NAME": "Oladapo John",
      AMOUNT: "₦200,000",
      STATUS: "Declined",
      "RAISED BY": "David John",
    },
    {
      id: 6,
      "S/N": 6,
      DATE: "20 Feb, 2023 @5:30am",
      "TRANSACTION ID": "TR-637153993...",
      "BANK NAME": {
        BANK_NAME: "UBA",
        BANK_IMAGE: "/bank-logo/uba.png",
      },
      "ACCOUNT NUMBER": 2190404040,
      "ACCOUNT NAME": "Oladapo John",
      AMOUNT: "₦200,000",
      STATUS: "Pending",
      "RAISED BY": "David John",
    },
    {
      id: 7,
      "S/N": 7,
      DATE: "20 Feb, 2023 @5:30am",
      "TRANSACTION ID": "TR-637153993...",
      "BANK NAME": {
        BANK_NAME: "ALATbyWema",
        BANK_IMAGE: "/bank-logo/alat.jfif",
      },
      "ACCOUNT NUMBER": 2190404040,
      "ACCOUNT NAME": "Oladapo John",
      AMOUNT: "₦200,000",
      STATUS: "Success",
      "RAISED BY": "David John",
    },
    {
      id: 8,
      "S/N": 8,
      DATE: "20 Feb, 2023 @5:30am",
      "TRANSACTION ID": "TR-637153993...",
      "BANK NAME": {
        BANK_NAME: "ALATbyWema",
        BANK_IMAGE: "/bank-logo/alat.jfif",
      },
      "ACCOUNT NUMBER": 2190404040,
      "ACCOUNT NAME": "Oladapo John",
      AMOUNT: "₦200,000",
      STATUS: "Pending",
      "RAISED BY": "David John",
    },
    {
      id: 9,
      "S/N": 9,
      DATE: "20 Feb, 2023 @5:30am",
      "TRANSACTION ID": "TR-637153993...",
      "BANK NAME": {
        BANK_NAME: "Stanbic IBTC",
        BANK_IMAGE: "/bank-logo/stanbic.jfif",
      },
      "ACCOUNT NUMBER": 2190404040,
      "ACCOUNT NAME": "Oladapo John",
      AMOUNT: "₦200,000",
      STATUS: "Pending",
      "RAISED BY": "David John",
    },
    {
      id: 10,
      "S/N": 10,
      DATE: "20 Feb, 2023 @5:30am",
      "TRANSACTION ID": "TR-637153993...",
      "BANK NAME": {
        BANK_NAME: "Zenith",
        BANK_IMAGE: "/bank-logo/zenith.png",
      },
      "ACCOUNT NUMBER": 2190404040,
      "ACCOUNT NAME": "Oladapo John",
      AMOUNT: "₦200,000",
      STATUS: "Pending",
      "RAISED BY": "David John",
    },
  ] 